name: flutter_weather_bg_example
description: Demonstrates how to use the flutter_weather_bg plugin.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  adv_flutter_weather:
    path: ..

  cupertino_icons: ^0.1.3

dependency_overrides:
  open_weather_client: 
    git:
      url: https://github.com/gslender/flutter_open_weather_package.git   
      ref: 9d8a7812c2f2a6ffbdc05c04161367489917ecb8   

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
