name: adv_flutter_weather
description: The adv weather background animation effect widget, covering 15 weather types, including sunny,rain,snow...
version: 1.0.0
homepage: https://github.com/gslender/adv_flutter_weather

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  open_weather_client: any
  intl: ^0.17.0

dependency_overrides:
  open_weather_client: 
    path: ../flutter_open_weather_package
    # git:
    #   url: https://github.com/gslender/flutter_open_weather_package.git   
    #   ref: 9d8a7812c2f2a6ffbdc05c04161367489917ecb8   

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - images/
